sudo: required

language: java

jdk: oraclejdk10

addons:
  sonarcloud:
    organization: "marcust-github"

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent jacoco:prepare-agent-integration install sonar:sonar

after_success:
  - mvn jacoco:report coveralls:report
  - mvn deploy --settings etc/settings.xml -DskipTests=true -B
