sudo: required

language: java

jdk: openjdk10

addons:
  sonarcloud:
    organization: "marcust-github"

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  mvn deploy --settings etc/settings.xml -DskipTests=true -B
 
