sudo: required

language: java

jdk: openjdk10

addons:
  sonarcloud:
    organization: "marcust-github"

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

services:
  - docker
